/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthView: typeof import('./views/AuthView.vue')['default']
    ConversationList: typeof import('./components/ConversationList.vue')['default']
    ConversationView: typeof import('./views/ConversationView.vue')['default']
    FriendList: typeof import('./components/FriendList.vue')['default']
    HomeView: typeof import('./views/HomeView.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    MessageList: typeof import('./components/MessageList.vue')['default']
    NotFoundView: typeof import('./views/NotFoundView.vue')['default']
    RegisterForm: typeof import('./components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetDisplayNameForm: typeof import('./components/SetDisplayNameForm.vue')['default']
    UserView: typeof import('./views/UserView.vue')['default']
  }
}
